name: Wearables
version: 1.1.0
author: Rappelr
main: com.rappelr.wearables.Wearables
api-version: 1.14
depend: [ItemsAdder, ProtocolLib]
commands:
  wearables:
    description: Wearables core command
    permission: wearables.admin
    usage: /<command>
permissions:
  wearables.admin:
    default: op